BASIS_OF_RECORD: HUMAN_OBSERVATION
BOUNDS:
- -73.591232
- -73.583851
- 45.513204
- 45.517895
GEOMETRY: POLYGON((-73.591232 45.513204, -73.591232 45.517895, -73.583851 45.517895,
  -73.583851 45.513204, -73.591232 45.513204))
TAXON_KEY: 7707728
HAS_COORDINATE: true
