gbif:
  BASIS_OF_RECORD: HUMAN_OBSERVATION
  GEOMETRY: POLYGON((-73.590474 45.515225, -73.587554 45.513902, -73.585494 45.516187,
    -73.590302 45.517751, -73.590474 45.515225))
  HAS_COORDINATE: true
  TAXON_KEY: 7707728
