gbif:
  BASIS_OF_RECORD: HUMAN_OBSERVATION
  GEOMETRY: POLYGON((-73.606526 45.51994, -73.623861 45.495157, -73.595027 45.485771,
    -73.569454 45.513204, -73.606526 45.51994))
  HAS_COORDINATE: true
  TAXON_KEY: 7707728
