gbif:
  COUNTRY: CA
  GEOMETRY: POLYGON((-73.509156 45.524824, -73.086303 46.045787, -71.444314 46.686379,
    -71.032444 46.821866, -70.203212 46.296853, -71.669469 45.014526, -74.519611 45.014526,
    -73.509156 45.524824))
  STATE_PROVINCE: Quebec
  TAXON_KEY: 7707728
  YEAR: 2010
